GET http://localhost:4000/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTkzNTc5MjksImV4cCI6MTYxOTM1Nzk0NCwiYXVkIjoiNjA4MmUxOGVlYmM5MGYxNDJjYTI2ZjE4IiwiaXNzIjoic2thcnRuZXIuY29tIn0.rY1Ptg5rGed3QunATuvl0J1hqWFtQc6QxjkdMaCPMMc
###
GET http://localhost:4000/posts

###
POST http://localhost:4000/auth/login
Content-Type: application/json

{
  "email": "123@gmail.com",
  "password": "123456"
}


###
POST http://localhost:4000/auth/register
Content-Type: application/json

{
  "email": "12345@gmail.com",
  "password": "123456"
}

###
POST http://localhost:4000/auth/refresh-token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTkzNTk3NzUsImV4cCI6MTYxOTM1OTgwNSwiYXVkIjoiNjA4MmUxOGVlYmM5MGYxNDJjYTI2ZjE4IiwiaXNzIjoic2thcnRuZXIuY29tIn0.4LYLfoyPs_tbF-KM8fkBeTRaozYfMDqzVyX4OnyndSc"
}

###
DELETE  http://localhost:4000/auth/logout 
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTkzNjIyMDUsImV4cCI6MTY1MDkxOTgwNSwiYXVkIjoiNjA4MmUxOGVlYmM5MGYxNDJjYTI2ZjE4IiwiaXNzIjoic2thcnRuZXIuY29tIn0.iJpTY6xNXoP1kbQLwc0o81oXfIL5qWVbLkNoJ6MdsE4"
}
